### PR TITLE
option to watch all files in folder

### PR DESCRIPTION
**Pull request by jaime-ez**
Hi, great module. I just wanted to watch all files in the folder and didn't found how to do it with the current settings. I added an option that if I set res: '*' it will watch all files in folder for a given window.
If there was already a way of doing it, please let me know.
Hope it helps! best, :)

### CODE REVIEW

**Comment by manidlou** [comment]
Thanks @jaime-ez. You are right. Originally, there was no way to watch all files in a dir. I like the idea of providing such an option. However, I like to know your idea about this,  if we set the option as `'*'`, then `res` would have 2 types, `{Array<String>}` and `{String}`. Don't you think it can be a little confusing then?

Alternatively, what do you think about providing this option by saying if you want this `bw` to be reloaded for any changes, that is watching all files in a dir for this `bw`, pass an empty `[]` for `res` of this `bw`? In that case, the `res` type would be kept consistent as well.

In the code, we could achieve this by something like

```js
if (win.bw && win.res && Array.isArray(win.res) &&
  (win.res.indexOf(path.basename(f)) !== -1 || win.res.length === 0)) {
  win.bw.reload()
}
```

Your thoughts?

**Comment by jaime-ez** [comment]
Hi @manidlou you're right, consistency is essential. I'll make a new commit with those modifications in place. And I just realized that I forced the code style I use ([standardjs](http://standardjs.com/index.html) - I like it because it's simple) on the main file... do you rather use another style?
Let me know what you think, best

**Comment by manidlou** [comment]
That's perfectly fine. `standardjs` is cool. I like it too.

**Comment by jaime-ez** [comment]
Great, pull request updated :)

**Comment by manidlou** [comment]
Thanks @jaime-ez. I really appreciate your help.

**Pull request merged**
